In [96]:
import pandas as pd
import os
import csv
import glob
from datetime import datetime
from functools import reduce

In [97]:
WEATHER_DATA_BASE_PATH = '../data/external/weather_data'
HOLIDAYS_BASE_PATH = '../data/external/holidays'

# Kreiranje podatkovnog okvira za vremensku prognozu

In [98]:
lisbon_weather_data_2015 = pd.read_csv(os.path.join(WEATHER_DATA_BASE_PATH, 'lisbon\\lisbon_weather_data_2015.csv'))
lisbon_weather_data_2016 = pd.read_csv(os.path.join(WEATHER_DATA_BASE_PATH, 'lisbon\\lisbon_weather_data_2016.csv'))
lisbon_weather_data_2017 = pd.read_csv(os.path.join(WEATHER_DATA_BASE_PATH, 'lisbon\\lisbon_weather_data_2017.csv'))

In [99]:
algarve_weather_data_2015 = pd.read_csv(os.path.join(WEATHER_DATA_BASE_PATH, 'algarve\\algarve_weather_data_2015.csv'))
algarve_weather_data_2016 = pd.read_csv(os.path.join(WEATHER_DATA_BASE_PATH, 'algarve\\algarve_weather_data_2016.csv'))
algarve_weather_data_2017 = pd.read_csv(os.path.join(WEATHER_DATA_BASE_PATH, 'algarve\\algarve_weather_data_2017.csv'))

In [100]:
lisbon_weather_data_2015.describe()

,tempmax,tempmin,temp,feelslikemax,feelslikemin,feelslike,dew,humidity,precip,precipprob,...,windspeed,winddir,sealevelpressure,cloudcover,visibility,solarradiation,solarenergy,uvindex,severerisk,moonphase
count,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,...,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,0.0,365.000000
mean,21.684110,13.863562,17.253699,21.635342,13.483562,17.101918,11.299178,70.715342,0.944364,31.780822,...,23.046301,227.114521,1020.215342,42.603836,10.989863,217.255616,18.762740,7.164384,NaN,0.482521
std,5.863551,4.166106,4.670161,5.806749,4.815748,4.903830,3.956657,13.566439,3.862379,46.626363,...,6.867291,121.519610,6.415172,23.977847,1.499444,96.036390,8.295006,2.347630,NaN,0.285404
min,7.200000,1.200000,4.100000,7.200000,-2.200000,1.900000,-0.600000,31.500000,0.000000,0.000000,...,7.400000,0.200000,1003.900000,0.000000,3.200000,31.300000,2.600000,1.000000,NaN,0.000000
25%,17.000000,11.000000,13.900000,17.000000,11.000000,13.900000,8.900000,62.400000,0.000000,0.000000,...,18.100000,100.400000,1016.200000,21.900000,10.500000,133.100000,11.400000,5.000000,NaN,0.250000
50%,21.100000,14.300000,17.300000,21.100000,14.300000,17.300000,11.900000,71.600000,0.000000,0.000000,...,21.800000,275.700000,1018.900000,41.800000,11.200000,219.600000,18.900000,8.000000,NaN,0.500000
75%,26.400000,17.100000,21.100000,26.400000,17.100000,21.100000,14.100000,80.300000,0.055000,100.000000,...,27.800000,331.300000,1024.600000,59.500000,12.000000,301.700000,26.000000,9.000000,NaN,0.730000
max,35.300000,23.400000,27.400000,35.200000,23.400000,27.100000,19.600000,97.300000,44.388000,100.000000,...,53.500000,359.800000,1041.000000,92.100000,16.500000,368.600000,31.800000,10.000000,NaN,0.980000

In [101]:
lisbon_weather_data_2015.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 33 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   name              365 non-null    object
 1   datetime          365 non-null    object
 2   tempmax           365 non-null    float64
 3   tempmin           365 non-null    float64
 4   temp              365 non-null    float64
 5   feelslikemax      365 non-null    float64
 6   feelslikemin      365 non-null    float64
 7   feelslike         365 non-null    float64
 8   dew               365 non-null    float64
 9   humidity          365 non-null    float64
 10  precip            365 non-null    float64
 11  precipprob        365 non-null    int64
 12  precipcover       365 non-null    float64
 13  preciptype        116 non-null    object
 14  snow              0 non-null      float64
 15  snowdepth         0 non-null      float64
 16  windgust          327 non-null    float64
 17  windspeed         365 non-null    float64
 18  winddir           365 non-null    float64
 19  sealevelpressure  365 non-null    float64
 20  cloudcover        365 non-null    float64
 21  visibility        365 non-null    float64
 22  solarradiation    365 non-null    float64
 23  solarenergy       365 non-null    float64
 24  uvindex           365 non-null    int64
 25  severerisk        0 non-null      float64
 26  sunrise           365 non-null    object
 27  sunset            365 non-null    object
 28  moonphase         365 non-null    float64
 29  conditions        365 non-null    object
 30  description       365 non-null    object
 31  icon              365 non-null    object
 32  stations          365 non-null    object
dtypes: float64(22), int64(2), object(9)
memory usage: 94.2+ KB

In [102]:
lisbon_weather_data_2015.merge(lisbon_weather_data_2016, how='outer').merge(lisbon_weather_data_2017, how='outer').to_csv(os.path.join(WEATHER_DATA_BASE_PATH, 'lisbon\\lisbon_weather_data.csv'), index=False)

In [103]:
algarve_weather_data_2015.merge(algarve_weather_data_2016, how='outer').merge(algarve_weather_data_2017, how='outer').to_csv(os.path.join(WEATHER_DATA_BASE_PATH, 'algarve\\algarve_weather_data.csv'), index=False)

C:\Temp\ipykernel_27548\2764141123.py:1: UserWarning: You are merging on int and float columns where the float values are not equal to their int representation.
  algarve_weather_data_2015.merge(algarve_weather_data_2016, how='outer').merge(algarve_weather_data_2017, how='outer').to_csv(os.path.join(WEATHER_DATA_BASE_PATH, 'algarve\\algarve_weather_data.csv'), index=False)

# Kreiranje podatkovnog okvira za praznike

In [104]:
all_holidays = {}

for country in os.listdir(HOLIDAYS_BASE_PATH):
    if os.path.isdir(os.path.join(HOLIDAYS_BASE_PATH, country)):
        all_holidays[country] = {}
        for year_file in glob.glob(os.path.join(HOLIDAYS_BASE_PATH, country, "*.txt")):
            try:
                year = os.path.basename(year_file).split('.')[0]
                all_holidays[country][year] = []

                with open(year_file, mode='r', encoding='utf-8') as file:
                    reader = csv.reader(file)
                    headers = next(reader)
                    date_idx = headers.index("Date")
                    name_idx = headers.index("Name")
                    type_idx = headers.index("Type")

                    for row in reader:

                        date = row[date_idx]
                        date = datetime.strptime(f'{date} {year}', '%d %b %Y')
                        date= date.strftime('%Y-%m-%d') 
                        name = row[name_idx]
                        type_ = row[type_idx]
                        all_holidays[country][year].append([date, name, type_])

            except Exception as e:
                print(f"Error prcessing file: {year_file}\nError: {e}")

In [105]:
holiday_portugal = pd.DataFrame(all_holidays['portugal']['2015'] + all_holidays['portugal']['2016'] + all_holidays['portugal']['2017'], columns=['date', 'name', 'type'])
holiday_portugal.to_csv(os.path.join(HOLIDAYS_BASE_PATH, 'portugal\\holidays.csv'), index=False)

In [106]:
holiday_france = pd.DataFrame(all_holidays['france']['2015'] + all_holidays['france']['2016'] + all_holidays['france']['2017'], columns=['date', 'name', 'type'])
holiday_france.to_csv(os.path.join(HOLIDAYS_BASE_PATH, 'france\\holidays.csv'), index=False)

In [107]:
holiday_germany = pd.DataFrame(all_holidays['germany']['2015'] + all_holidays['germany']['2016'] + all_holidays['germany']['2017'], columns=['date', 'name', 'type'])
holiday_germany.to_csv(os.path.join(HOLIDAYS_BASE_PATH, 'germany\\holidays.csv'), index=False)

In [108]:
holiday_italy = pd.DataFrame(all_holidays['italy']['2015'] + all_holidays['italy']['2016'] + all_holidays['italy']['2017'], columns=['date', 'name', 'type'])
holiday_italy.to_csv(os.path.join(HOLIDAYS_BASE_PATH, 'italy\\holidays.csv'), index=False)

In [109]:
holiday_spain = pd.DataFrame(all_holidays['spain']['2015'] + all_holidays['spain']['2016'] + all_holidays['spain']['2017'], columns=['date', 'name', 'type'])
holiday_spain.to_csv(os.path.join(HOLIDAYS_BASE_PATH, 'spain\\holidays.csv'), index=False)

In [110]:
holiday_united_kingdom = pd.DataFrame(all_holidays['united_kingdom']['2015'] + all_holidays['united_kingdom']['2016'] + all_holidays['united_kingdom']['2017'], columns=['date', 'name', 'type'])
holiday_united_kingdom.to_csv(os.path.join(HOLIDAYS_BASE_PATH, 'united_kingdom\\holidays.csv'), index=False)

### Finding the intersection of the holidays

In [111]:
holiday_intersection = holiday_portugal[['date', 'name', 'type']]
holiday_intersection = holiday_intersection.merge(holiday_france[['date']], how='inner', on='date')
holiday_intersection = holiday_intersection.merge(holiday_germany[['date']], how='inner', on='date')
holiday_intersection = holiday_intersection.merge(holiday_italy[['date']], how='inner', on='date')
holiday_intersection = holiday_intersection.merge(holiday_spain[['date']], how='inner', on='date')
holiday_intersection = holiday_intersection.merge(holiday_united_kingdom[['date']], how='inner', on='date')

In [112]:
holiday_intersection.to_csv(os.path.join(HOLIDAYS_BASE_PATH, 'holidays_intersection.csv'), index=False)